In [1]:
#Anmol Bansal 19BCE0630
#importing the dependencies

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_iris
from sklearn.utils import shuffle

In [2]:
#importing the raw dataset

df = pd.read_csv("Iris.csv")

In [3]:
#viewing the dataset

df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [4]:
#dropping useless columns and shuffling the dataset

df.drop("Id", axis = 1, inplace = True)
df = shuffle(df)

In [5]:
#label encoding the output classes

cat = list(df['Species'].unique())
cat_label = dict(zip(cat, range(0, len(cat))))
df['Species'] = df['Species'].map(cat_label)

In [6]:
#Viewing the preprocessed data

df

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
10             5.4           3.7            1.5           0.2        0
126            6.2           2.8            4.8           1.8        1
149            5.9           3.0            5.1           1.8        1
53             5.5           2.3            4.0           1.3        2
143            6.8           3.2            5.9           2.3        1
..             ...           ...            ...           ...      ...
72             6.3           2.5            4.9           1.5        2
84             5.4           3.0            4.5           1.5        2
55             5.7           2.8            4.5           1.3        2
9              4.9           3.1            1.5           0.1        0
5              5.4           3.9            1.7           0.4        0

[150 rows x 5 columns]

In [7]:
#Seperating the dataset into training and testing set

X, y = df.drop("Species", axis = 1), df['Species']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 42, train_size = 0.66)

In [8]:
#viewing training dataset

X_train

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
43             5.0           3.5            1.6           0.6
130            7.4           2.8            6.1           1.9
26             5.0           3.4            1.6           0.4
101            5.8           2.7            5.1           1.9
36             5.5           3.5            1.3           0.2
..             ...           ...            ...           ...
131            7.9           3.8            6.4           2.0
109            7.2           3.6            6.1           2.5
29             4.7           3.2            1.6           0.2
148            6.2           3.4            5.4           2.3
4              5.0           3.6            1.4           0.2

[99 rows x 4 columns]

In [8]:
y_train

95     2
82     2
10     0
142    1
83     2
      ..
37     0
116    1
15     0
50     2
112    1
Name: Species, Length: 99, dtype: int64

In [9]:
#viewing the test data

X_test

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
63             6.1           2.9            4.7           1.4
70             5.9           3.2            4.8           1.8
145            6.7           3.0            5.2           2.3
44             5.1           3.8            1.9           0.4
136            6.3           3.4            5.6           2.4
115            6.4           3.2            5.3           2.3
20             5.4           3.4            1.7           0.2
139            6.9           3.1            5.4           2.1
13             4.3           3.0            1.1           0.1
78             6.0           2.9            4.5           1.5
51             6.4           3.2            4.5           1.5
33             5.5           4.2            1.4           0.2
137            6.4           3.1            5.5           1.8
92             5.8           2.6            4.0           1.2
52             6.9           3.1            4.9           1.5
93             5.0           2.3            3.3           1.0
59             5.2           2.7            3.9           1.4
26             5.0           3.4            1.6           0.4
75             6.6           3.0            4.4           1.4
129            7.2           3.0            5.8           1.6
85             6.0           3.4            4.5           1.6
128            6.4           2.8            5.6           2.1
27             5.2           3.5            1.5           0.2
2              4.7           3.2            1.3           0.2
106            4.9           2.5            4.5           1.7
72             6.3           2.5            4.9           1.5
117            7.7           3.8            6.7           2.2
100            6.3           3.3            6.0           2.5
49             5.0           3.3            1.4           0.2
130            7.4           2.8            6.1           1.9
74             6.4           2.9            4.3           1.3
120            6.9           3.2            5.7           2.3
132            6.4           2.8            5.6           2.2
22             4.6           3.6            1.0           0.2
76             6.8           2.8            4.8           1.4
84             5.4           3.0            4.5           1.5
119            6.0           2.2            5.0           1.5
64             5.6           2.9            3.6           1.3
143            6.8           3.2            5.9           2.3
56             6.3           3.3            4.7           1.6
103            6.3           2.9            5.6           1.8
73             6.1           2.8            4.7           1.2
60             5.0           2.0            3.5           1.0
40             5.0           3.5            1.3           0.3
38             4.4           3.0            1.3           0.2
71             6.1           2.8            4.0           1.3
127            6.1           3.0            4.9           1.8
110            6.5           3.2            5.1           2.0
39             5.1           3.4            1.5           0.2
7              5.0           3.4            1.5           0.2
46             5.1           3.8            1.6           0.2

In [10]:
y_test

63     2
70     2
145    1
44     0
136    1
115    1
20     0
139    1
13     0
78     2
51     2
33     0
137    1
92     2
52     2
93     2
59     2
26     0
75     2
129    1
85     2
128    1
27     0
2      0
106    1
72     2
117    1
100    1
49     0
130    1
74     2
120    1
132    1
22     0
76     2
84     2
119    1
64     2
143    1
56     2
103    1
73     2
60     2
40     0
38     0
71     2
127    1
110    1
39     0
7      0
46     0
Name: Species, dtype: int64

In [11]:
#Instantiating Decision Tree Object

dt = DecisionTreeClassifier()

In [12]:
#fitting the model on training data

dt.fit(X_train, y_train)

DecisionTreeClassifier()

In [13]:
#predicting the model on test data

y_pred = dt.predict(X_test)

In [14]:
#predicted values

y_pred

array([2, 1, 1, 0, 1, 1, 0, 1, 0, 2, 2, 0, 1, 2, 2, 2, 2, 0, 2, 1, 2, 1,
       0, 0, 2, 2, 1, 1, 0, 1, 2, 1, 1, 0, 2, 2, 2, 2, 1, 2, 1, 2, 2, 0,
       0, 2, 1, 1, 0, 0, 0])

In [15]:
#printing the classification report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       0.94      0.89      0.91        18
           2       0.90      0.95      0.92        19

    accuracy                           0.94        51
   macro avg       0.95      0.95      0.95        51
weighted avg       0.94      0.94      0.94        51



In [16]:
#printing the confusion matrix

print(confusion_matrix(y_test, y_pred))

[[14  0  0]
 [ 0 16  2]
 [ 0  1 18]]


In [17]:
#printing the accuracy of the dataset

print(dt.score(X_test, y_test))

0.9411764705882353
